name: Unittest and build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication (npm ci bug workaround)
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
      - name: build
        run: npm run build
